version: '3.8'

services:
  postgres:
    image: postgres:16  # Güncel ve stabil bir sürüm
    container_name: arslancadb_container
    ports:
      - "5432:5432"  # Bilgisayarının 5432 portunu konteynerin 5432 portuna bağlar
    environment:
      POSTGRES_USER: postgres      # spring.datasource.username ile aynı
      POSTGRES_PASSWORD: 1234      # spring.datasource.password ile aynı
      POSTGRES_DB: arslancadb      # Url'deki /arslancadb ile aynı
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Verilerin kalıcı olması için (Docker'ı kapatsan bile veri silinmez)
    restart: always

volumes:
  postgres_data: